version: "3"

services:
  redis:
      container_name: redis-reuse
      image: gukjang/redis-reuse:1.0.0
      restart: always
      networks:
          - network-reuse
      ports:
          - 6379:6379
